remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-multiple-languages-plugin

languages: ["en", "pt-BR"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: en
languageNames:
  de: Portugues
  en: English
